Repository wafarifki/Hacktoberfest_2022, pull requests merged in 2022-10, with the labels that each got.

#1 feat: create new file to contribute
  iceboy1406.js
Labels: hacktoberfest-accepted

#2 Create anime.js
  anime.js
Labels: hacktoberfest-accepted, HACKTOBERFEST-ACCEPTED.

#3 Create main.py
  main.py
Labels: hacktoberfest-accepted, HACKTOBERFEST-ACCEPTED., hacktoberfest

#4 Create rahulsust.cpp
  rahulsust.cpp
Labels: hacktoberfest-accepted, HACKTOBERFEST-ACCEPTED., hacktoberfest

#5 update contributing.md
  CONTRIBUTING.md
Labels: hacktoberfest-accepted, HACKTOBERFEST-ACCEPTED., hacktoberfest

#6 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: hacktoberfest-accepted, HACKTOBERFEST-ACCEPTED., hacktoberfest

#7 Rapihin nomor 4
  CONTRIBUTING.md
Labels: hacktoberfest-accepted, HACKTOBERFEST-ACCEPTED., hacktoberfest

#8 add new file
  CONTRIBUTING.md
  EmailValidator.go
Labels: hacktoberfest-accepted, HACKTOBERFEST-ACCEPTED., hacktoberfest

#9 Create mewxz029.js App
  CONTRIBUTING.md
  mewxz029.js
Labels: hacktoberfest-accepted, HACKTOBERFEST-ACCEPTED., hacktoberfest

#10 add zippyshare_downloader.py & edit CONTRIBUTING.md
  CONTRIBUTING.md
  zippyshare_downloader.py
Labels: hacktoberfest-accepted, HACKTOBERFEST-ACCEPTED., hacktoberfest

#14 Membuat folder agar lebih rapi
  C/rahulsust.cpp
  Golang/EmailValidator.go
  Javascript/anime.js
  Javascript/iceboy1406.js
  Javascript/mewxz029.js
  Python/main.py
  README.md
Labels: hacktoberfest-accepted, HACKTOBERFEST-ACCEPTED., hacktoberfest

#11 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: hacktoberfest-accepted, HACKTOBERFEST-ACCEPTED., hacktoberfest

#12 add contribute
  CONTRIBUTING.md
  generate-random-number.html
Labels: hacktoberfest-accepted, HACKTOBERFEST-ACCEPTED., hacktoberfest

#13 feat: palindrom javascript
  CONTRIBUTING.md
  palindrome.js
Labels: hacktoberfest-accepted, HACKTOBERFEST-ACCEPTED., hacktoberfest

#16 added a project on a Game
  CONTRIBUTING.md
  JavaScript Dragon Game/JavaScript Dragon Game/bg.png
  JavaScript Dragon Game/JavaScript Dragon Game/bg1.gif
  JavaScript Dragon Game/JavaScript Dragon Game/dino.png
  JavaScript Dragon Game/JavaScript Dragon Game/dragon.png
  JavaScript Dragon Game/JavaScript Dragon Game/gameover.mp3
  JavaScript Dragon Game/JavaScript Dragon Game/index.html
  JavaScript Dragon Game/JavaScript Dragon Game/music.mp3
  JavaScript Dragon Game/JavaScript Dragon Game/script.js
  JavaScript Dragon Game/JavaScript Dragon Game/style.css
Labels: hacktoberfest-accepted, HACKTOBERFEST-ACCEPTED., hacktoberfest

#17 added file functionReturningFunction
  CONTRIBUTING.md
  blockVsFunctionScope.js
  functionReturningFunction.js
Labels: hacktoberfest-accepted, HACKTOBERFEST-ACCEPTED., hacktoberfest

#18 Feature: Lyrics Finder
  Javascript/LyricsFinder.js
Labels: hacktoberfest-accepted, HACKTOBERFEST-ACCEPTED., hacktoberfest

#19 Simple snake game in vanilla js
  CONTRIBUTING.md
  snake-js.html
Labels: hacktoberfest-accepted, HACKTOBERFEST-ACCEPTED., hacktoberfest

#20 create file hello python
  hello_world.py
Labels: hacktoberfest-accepted, HACKTOBERFEST-ACCEPTED., hacktoberfest

#21 Update main.py
  main.py
Labels: hacktoberfest-accepted, HACKTOBERFEST-ACCEPTED., hacktoberfest

#22 add emailvalidator use php
  CONTRIBUTING.md
  EmailValidator.php
Labels: hacktoberfest-accepted, HACKTOBERFEST-ACCEPTED., hacktoberfest

#23 add palindromChecker use Typescript
  CONTRIBUTING.md
  palindromCheking.ts
Labels: hacktoberfest-accepted, HACKTOBERFEST-ACCEPTED., hacktoberfest

#25 Add Folder Dart & Example Looping in dart
  CONTRIBUTING.md
  Dart/Looping.dart
Labels: hacktoberfest-accepted, HACKTOBERFEST-ACCEPTED., hacktoberfest

#26 Tetris Animation
  CONTRIBUTING.md
  tetris_rain_niirmaaltwaatii.html
Labels: hacktoberfest-accepted, HACKTOBERFEST-ACCEPTED., hacktoberfest

#27 Hecktoberfest -2022
  Find the Runner-Up Score.py
  Nested_List.py
Labels: hacktoberfest-accepted, HACKTOBERFEST-ACCEPTED., hacktoberfest

#28 add meowcrafty.js
  CONTRIBUTING.md
  Javascript/meowcraftY.js
Labels: hacktoberfest-accepted, HACKTOBERFEST-ACCEPTED., hacktoberfest

#29 Program for Kadanes Algorithm
  Java/KadanesAlgo.java
Labels: hacktoberfest-accepted, HACKTOBERFEST-ACCEPTED., hacktoberfest

#32 Add uuid generator
  Web App/uuid-generator/README.md
  Web App/uuid-generator/index.html
Labels: hacktoberfest-accepted, HACKTOBERFEST-ACCEPTED., hacktoberfest

#33 add file NomorHPValidator.go
  Golang/NomorHPValidator.go
Labels: hacktoberfest-accepted, HACKTOBERFEST-ACCEPTED., hacktoberfest

#39 Create console.ts
  CONTRIBUTING.md
  console-generator.ts
Labels: hacktoberfest-accepted, HACKTOBERFEST-ACCEPTED., hacktoberfest
